modLoader = "javafml"
loaderVersion = "[37,)"
issueTrackerURL = "https://github.com/modmuss50/Retro-Exchange/issues"
license = "MIT"

[[mods]]
modId = "retroexchange"
version = "${version}"
displayName = "Retro Exchange"
authors = "modmuss50, LatvianModder"
description = '''
Retro Exchange
'''
license = "MIT"

[[dependencies.retroexchange]]
modId = "forge"
mandatory = true
versionRange = "[37.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.retroexchange]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.retroexchange]]
modId = "architectury"
mandatory = true
versionRange = "[2.0.0,)"
ordering = "AFTER"
side = "BOTH"